### PR TITLE
fix(iOS): don't automatically prefix the `domain` with at `.` in `set()` method

### PR DESCRIPTION
**Pull request by jackmu95**
# Summary

#45 introduced a change for the `set()` method on iOS to always include a trailing `.` for the `domain` (to be in-line with Android).

While this might make sense - it is not intended behavior for iOS and can cause issues.
I use this package to sync cookies from `NSHTTPCookieStorage` to `WKHTTPCookieStore` and this change caused issues since the cookie values aren't actually the same anymore.

Example:
```js
export const syncCookies = async ({ url }) => {
  if (IS_IOS) {
    try {
      const cookies = await CookieManager.get(url);
      for (const cookieName in cookies) {
        await CookieManager.set(url, cookies[cookieName], true);
      }
    } catch (error) {
      return false;
    }
  }

  return true;
};
```

I think we should stick to the default platform behavior and leave this up to the users

## Checklist

- [x] I have tested this on a device and a simulator
- [ ] I added the documentation in `README.md`
- [ ] I mentioned this change in `CHANGELOG.md`
- [ ] I updated the typed files (TS and Flow)
- [ ] I added a sample use of the API in the example project (`example/App.js`)

### CODE REVIEW

**Comment by safaiyeh** [comment]
Thanks for the PR @jackmu95! 

Any thoughts on this @YoliFD?

**Comment by jackmu95** [comment]
@safaiyeh Any update on this?
I still think this is a major bug and should be resolved ASAP.

Running this fix in production for over a month now; without issues :)

**Comment by safaiyeh** [comment]
Sounds good @jackmu95 thanks for making the PR. I have to move the CI pipeline to this new org first before I can merge it in, ill merge this in once I can

**Comment by xavier-villelegier** [comment]
@safaiyeh is there any reason that we still add a trailing `.` on Android ? I pretty much have the same issue than @jackmu95 where I wanna get cookies, clear all of them, and re-set some of them (it's actually the only way to remove only some cookies as `clearByName` is iOS only), and they end up not being the same because of the trailing `.` at the beginning, shouldn't this be up to the user ?

**Pull request merged**
